version: "3.9"

services:
  database:
    container_name: postgres_fast_api
    image: postgres:16-4-alpine
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
